---
- name: Install application Python dependencies for development and test
  pip: chdir={{ django_home }}/requirements requirements={{ item }}.txt
  with_items:
    - development
    - test
  when: "['development', 'test'] | some_are_in(group_names)"
  notify:
    - Restart rf-app

- name: Install application Python dependencies for production
  pip: chdir="{{ django_home }}/requirements" requirements=production.txt
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart rf-app

- name: Install Python dependencies for geoprocessing
  pip: chdir="{{ django_home }}/requirements" requirements=workers.txt
  environment:
    C_INCLUDE_PATH: "/usr/include/gdal"
    CPLUS_INCLUDE_PATH: "/usr/include/gdal"
  notify:
    - Restart rf-app
